---
title: "Candidate Match Report"
author: "Michael Haseley"
date: "November 22, 2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
empdata <- read.csv("EmpData.csv")
comdata <- read.csv("CompanyData.csv")
pacedata <- read.csv("CompanyPace.csv")
```

# Candidate
# Profile Match
# Report

## Candidate: XXXXXXXXXXX
## Company: XYZ
## Position: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

## Bin Test


```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

## App Test


```{r tabsets, echo=FALSE}
shinyAppDir(
  system.file("examples/06_tabsets", package = "shiny"),
  options = list(
    width = "100%", height = 550
  )
)
```

## Cognitive Match

```{r cognitive, echo=FALSE}
library(plotly)
p <- plot_ly(
  plotly::hobbs, r = ~comdata$CogNeed, t = ~empdata$Cog, color = ~nms, alpha = 0.5, type = "scatter"
)
layout(p, title = "Cognitive Match", plot_bgcolor = toRGB("grey90"))
```


## Soft Skills Match

```{r soft, echo=FALSE}
library(plotly)
p <- plot_ly(
  plotly::hobbs, r = ~comdata$CogNeed, t = ~empdata$Cog, color = ~nms, alpha = 0.5, type = "scatter"
)
layout(p, title = "Cognitive Match", plot_bgcolor = toRGB("grey90"))
```


## Personality Match

```{r person, echo=FALSE}
library(plotly)
p <- plot_ly(
  plotly::hobbs, r = ~comdata$CogNeed, t = ~empdata$Cog, color = ~nms, alpha = 0.5, type = "scatter"
)
layout(p, title = "Cognitive Match", plot_bgcolor = toRGB("grey90"))
```

## Horizontal Bar Test

```{r Hbar, echo=FALSE}
library(plotly)

y <- c('grit', 'Learning Orientation')
EM_C <- c(4, 3)
CA_P <- c(2, 3)
data <- data.frame(y, EM_C, CA_P)

p <- plot_ly(data, x = ~EM_C, y = ~y, type = 'bar', orientation = 'h', name = 'Employer',
        marker = list(color = 'rgba(246, 78, 139, 0.6)',
                      line = list(color = 'rgba(246, 78, 139, 1.0)',
                                  width = 3))) %>%
  add_trace(x = ~CA_P, name = 'Candidate',
            marker = list(color = 'rgba(58, 71, 80, 0.6)',
                          line = list(color = 'rgba(58, 71, 80, 1.0)',
                                      width = 3))) %>%
  layout(barmode = 'stack',
         xaxis = list(title = ""),
         yaxis = list(title =""))
```
